plugins {
    id 'com.android.application'
}

android {
    namespace 'electrostock.com'
    compileSdkVersion 35
    defaultConfig {
        applicationId "electrostock.com"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 4
        versionName "1.0.3"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.gms:play-services-ads:25.4.0'
    implementation 'com.google.android.ump:user-messaging-platform:4.0.0'
}
